### ISSUE TITLE
Support attachments

### ISSUE THREAD

**Issue by tomblench** [cloudant-labs/envoy#117]
This should include all of the various ways if interacting with attachments:
- Inline base64 (may already work)
- HEAD/GET/PUT/DELETE `/db/docid/attachment`
- GET `multipart/related`
- Dealing with compression appropriately (hopefully just a case of piping data through and ensuring `accept-encoding`/`content-encoding` headers are relayed properly).

**Comment by burzakovskiy** [comment]
Have you got any plans about attachment support? This feature becomes very important for us.

**Comment by glynnbird** [comment]
@burzakovskiy I'm working on this right now.

**Comment by glynnbird** [comment]
Attachment support is in 0.3.0 of Envoy.
