### ISSUE TITLE
sync-android can't accept cookie

### ISSUE THREAD

**Issue by burzakovskiy** [cloudant-labs/envoy#124]
Configuration: Envoy deployed on Bluemix with non-Bluemix Cloudant db on Porter cluster,  and latest versions of Cloudant library for Android.
Pull and Push requests cause the same error:
_E/CookieInterceptor: Failed to get cookie from server, response code %s, cookie authentication will not be attempted again_
and
_CouchException: error: Unknown error, reason: Unkown reason, statusCode: 403, msg: Error deserializing server response, cause: java.io.FileNotFoundException: https://<envoy-host>.mybluemix.net:443/envoy_

**Comment by tomblench** [comment]
@burzakovskiy this is a known limitation of envoy. See [my sample code](https://github.com/tomblench/EnvoyDemo/blob/master/app/src/main/java/cloudant/com/envoydemo/PullDataTask.java#L71) for an example of how to use basic authentication instead.

**Comment by burzakovskiy** [comment]
@tomblench thanks, it works with with BasicAuthInterceptor
