### ISSUE TITLE
Envoy creates redundant documents in db

### ISSUE THREAD

**Issue by burzakovskiy** [cloudant-labs/envoy#126]
Every time when push or pull replication is started between android device and remote cloudant db, envoy creates extra document in db with user name and password in plain text. After 6 replications I had 6 such documents
{
  "_id": "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3-58f45b95-3c67-4233-a538-184ef051ea06",
  "_rev": "1-45ecf200995c8afc6ba1421ee5e21a7f",
  "name": "test",
  "password": "password"
}

**Comment by willholley** [comment]
Oof - it looks as though POSTs to `_session` get translated into a document POST to the database - clearly a bug in Envoy cc @glynnbird

**Comment by xpqz** [comment]
Fixed in https://github.com/cloudant-labs/envoy/pull/132
