### ISSUE TITLE
Pull replication on new device issue

### ISSUE THREAD

**Issue by burzakovskiy** [cloudant-labs/envoy#130]
Does Envoy affect sync-android replication mechanism?
I've observed the following:
When user replicates data between Andoid device and remote Cloudant db through Envoy and reinstalls app or installs it on another device nothing is pulled from remote db.
I've tried to replicate directly to Cloudant, created API key with read+write permissions and replication and data was pulled to new device.

**Comment by willholley** [comment]
That should work. Are both devices logged in as the same Envoy user? Are you able to provide a log of requests made against Envoy?

**Comment by burzakovskiy** [comment]
That was the issue on our side. thanks
