### ISSUE TITLE
Why I can't properly _logout ??

### ISSUE THREAD

**Issue by numerized** [cloudant-labs/envoy#156]
Hi There, 

I'm just so excited about all the possibilities that envoy gives to our team, we are really enjoying envisioning it for our next customers. The thing is, everything works perfectly but the _logout route.

The logout route returns a nice and clean ok true client side:
```
{"ok":true}
```

and a nice reply server side:
```
::ffff:86.23.2.52 - - [16/Nov/2016:21:38:06 +0000] "GET /_logout HTTP/1.1" 200 11 "http://localhost:8100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
```

but I appear to be still logged in, when I try a get _auth client side:
```
{"loggedin":true,"username":"1479300601"}
```

server side:
```
::ffff:86.23.2.52 - - [16/Nov/2016:21:38:10 +0000] "GET /_auth HTTP/1.1" 200 41 "http://localhost:8100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36"
```

I tried to install redis and redis-connect. It's working brillantly too but no way of logging out.
I tried to pass in PRODUCTION mode, same.

I'd like to be unauthed our platform is going to be hosted on tablets where users have to logout before the next user can use the same tablet.

Do I miss something ???

My stack

Ionic2
cloudant
pouchdb-envoy

**Comment by numerized** [comment]
Ok I've found the reason why _logout didn't work properly ....

Please add to your doc that you need to pass some credentials to the logout GET

This is the angular2 way :

```
let bodyString = null;
let headers = new Headers({ 'Content-Type': 'application/x-www-form-urlencoded' }); 
let options = new RequestOptions({ headers: headers, withCredentials:true });

    return this.http.get('http://95.138.171.135:9000/_logout', options)
        .map((res:Response) => res.json())
        .catch((error:any) => Observable.throw(error.json().error || 'Server error'));
```

**Comment by glynnbird** [comment]
The `GET /_logout` call simply deletes your user data from the session. 

https://github.com/cloudant-labs/envoy/blob/master/lib/plugins/auth/default.js#L149

You're right that we always return "{ok: true}". That could be changed so that it only returns true if there was a user in session already. If you call `GET /_logout` without a cookie, then Envoy doesn't know which session you are participating in and will create a new session.

**Comment by numerized** [comment]
yes true, 

but from my tests, and I've just redone it now, if I don't send {withCredentials:true} in my header I'm not logged out and session persists when reconnecting with a different envoy user, the previous user db contents are pushed to the new db.

When I add withCredentials:true to my logout header then the logout is correct.

Are you with me ?

**Comment by snapedia** [comment]
The solution mentioned by numerized worked great for me too.  All I did was add the content-type header and the withCredentials:true to my http GET and it fixed the issue where my express session was remaining the same between two different envoy users, causing one to essentially read/write into the other.  Thanks for this!
