### ISSUE TITLE
allow custom plugins

### ISSUE THREAD

**Issue by Xiphe** [cloudant-labs/envoy#161]
I'd love to play around with custom plugins but still use the core of this tool.

Therefore it would be great I could just

```sh
export ENVOY_AUTH="~/my/custom/AuthPlugin"
enovy
```

**Comment by glynnbird** [comment]
That should be doable. At the moment, a plugin has to reside in the plugins directory, but that could be changed: https://github.com/cloudant-labs/envoy/blob/master/lib/auth.js#L1

**Comment by Xiphe** [comment]
yeah, just noted that. working on a PR :)

**Comment by glynnbird** [comment]
Excellent news! :)
