### ISSUE TITLE
Add custom auth

### ISSUE THREAD

**Issue by MichalZak** [cloudant-labs/envoy#169]
Is there a way to write a custom auth. For example i want to be  able to use jwt, or token.

Mike

**Comment by glynnbird** [comment]
There is @MichalZak. The auth system is a plugin. You can provide your own replacement plugin when you start up Envoy by passing the path of your plugin file as the `ENVOY_AUTH` environment variable.

Here's the default plugin that can be used as a starting point:

https://github.com/cloudant-labs/envoy/blob/master/lib/plugins/auth/default.js

- init - called at startup to perform setup actions
- newUser - create a new user
- getUser - get a user by unique id
- isAuthenticated - Express middleware to decide whether the current request has the authority to proceed
- unauthorized - reply to the caller with a response to show that they were not authorised
- routes - custom routes to be added to the Express app when not in production mode.

**Comment by MichalZak** [comment]
Hey thanks for the  fast reply, appreciated

Mike
