### ISSUE TITLE
hard coded db name in couchdb_user.js

### ISSUE THREAD

**Issue by jon123** [cloudant-labs/envoy#170]
Referring to the code below at the start of `lib/plugins/auth/couchdb_user.js` 
```
// called at startup
var init =  function(callback) {
  usersdb = app.cloudant.db.use(USERS_DATABASE_NAME);
  app.cloudant.db.create('_users', function(err, body, header) {
`````
If I follow the logic, the `app.cloudant.db.create('_users'` is intended to check if the user's database exists and if not create it.  Should this not be `app.cloudant.db.create(USERS_DATABASE_NAME`  ?

**Comment by glynnbird** [comment]
@jon123 you're quite right. Fixing now.
