### ISSUE TITLE
Logging on Bluemix

### ISSUE THREAD

**Issue by xpqz** [cloudant-labs/envoy#18]
We should look at logging -- is there a standard logging approach/facility for Bluemix? At the moment we use `morgan` to log to file.

**Comment by glynnbird** [comment]
Just need to output stuff to the terminal, then Bluemix picks it up. I've used the [debug](https://www.npmjs.com/package/debug) package before. It allows the user to choose which packages' logging to output e.g.

```
# just cloudant library debug
DEBUG=cloudant node app.js
# nano + cloudant debug
DEBUG=cloudant,nano node app.js
# envoy debug
DEBUG=envoy node app.js
```

It would mean sprinkling calls to `debug` everywhere in the code and the user can choose to see the messages by setting `DEBUG` env variable at run time.

**Comment by glynnbird** [comment]
The debugging (using DEBUG) is sufficient for the moment. We can always add our own Envoy-level debugging messages too if we want. I ended up making the Morgan-powered logging go to stdout and allowed it to be configured using an environment variable e.g

```sh
> LOG_FORMAT=combined node app
::1 - glynn [26/May/2016:18:28:27 +0000] "PUT /mbaas/c HTTP/1.1" 200 63 "-" "curl/7.43.0"
::1 - bob [26/May/2016:18:28:28 +0000] "PUT /mbaas/d HTTP/1.1" 200 63 "-" "curl/7.43.0"
```
