### ISSUE TITLE
pouchdb 6.2.0 update?

### ISSUE THREAD

**Issue by numerized** [cloudant-labs/envoy#180]
Hello Glenn, 

any time to update Pouchdb to 6.2.0 it fixes pouchdb-find quite importantly.

Cheers mate.

**Comment by glynnbird** [comment]
sure thing @numerized  I'll do that today.

**Comment by glynnbird** [comment]
Fixed in version 0.4.4

**Comment by numerized** [comment]
Cool !!! Going to test that !

**Comment by numerized** [comment]
It Works ! Thanks!
