### ISSUE TITLE
ETIMEDOUT with live sync

### ISSUE THREAD

**Issue by tarr11** [cloudant-labs/envoy#186]
I am testing out this library, and after 25 seconds I receive ETIMEOUT.  After that, sync no longer works.  When I connect directly to my CouchDB, this doesn't happen.

The offending network call:
`http://localhost:8000/envoy/_changes?timeout=25000&style=all_docs&feed=longpoll&heartbeat=10000&since=173-g1AAAACbeJzLYWBgYMpgTmEQTM4vTc5ISXLIyU9OzMnILy7JAUklMiTV____PyuDOTEsFyjAbp5mmmyUkoxNAx5j8liAJEMDkPoPNS0cbJpxqnmagXEaNn1ZALvGMa8&limit=98`

StackTrace:
```
CustomPouchError {code: "ETIMEDOUT", status: 0, result: Object}
(anonymous) @ store.ts:43
EventEmitter.emit @ events.js:81
(anonymous) @ index-browser.js:12066
Promise rejected (async)
g @ events.js:165
EventEmitter.emit @ events.js:81
backOff @ index-browser.js:11272
completeReplication @ index-browser.js:11596
abortReplication @ index-browser.js:11567
onChangesError @ index-browser.js:11670
Promise rejected (async)
opts.complete @ index-browser.js:1576
fetched @ index-browser.js:9521
(anonymous) @ index-browser.js:8505
xhr.onreadystatechange @ index-browser.js:8403
timeoutReq @ index-browser.js:8299
XMLHttpRequest.send (async)
xhRequest @ index-browser.js:8413
ajax$1 @ index-browser.js:8432
ajaxCore$1 @ index-browser.js:8502
ajax @ index-browser.js:8559
ajax$$1 @ index-browser.js:8762
(anonymous) @ index-browser.js:9482
Promise resolved (async)
setup @ index-browser.js:8793
fetch @ index-browser.js:9481
(anonymous) @ index-browser.js:9537
nextTick @ browser.js:57
characterData (async)
scheduleDrain @ browser.js:15
immediate @ browser.js:67
fetched @ index-browser.js:9537
onSuccess @ index-browser.js:8482
(anonymous) @ index-browser.js:8524
xhr.onreadystatechange @ index-browser.js:8391

```

**Comment by tarr11** [comment]
Adding `{ retry: true }` to my PouchDB sync call solved this

**Comment by willholley** [comment]
I think this is related to https://github.com/pouchdb/pouchdb/issues/6510 - there's a pending PR for Pouch to fix it.

Will Holley 
Technical Advisor
IBM Watson Data Platform

> On 28 May 2017, at 18:21, Douglas Tarr <notifications@github.com> wrote:
> 
> Adding { retry: true } to my PouchDB sync call solved this
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
Unless stated otherwise above:
IBM United Kingdom Limited - Registered in England and Wales with number 741598. 
Registered office: PO Box 41, North Harbour, Portsmouth, Hampshire PO6 3AU
