### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by motin** [cloudant-labs/envoy#193]
There are no signs of activity for over a year. In the case of abandonment, could you kindly inform about what the current state of art / alternative solution to the Cloudant one-database-per-user challenges?

**Comment by glynnbird** [comment]
It just so happens that I'm revamping this project :)

**Comment by motin** [comment]
That is great news! Looking forward to it! Please post any RFCs or discussion issues that you'd like to get input on, thanks :)
