### ISSUE TITLE
Envoy doesn't enable CORS, so can't be used from a browser.

### ISSUE THREAD

**Issue by glynnbird** [cloudant-labs/envoy#2]
When using Envoy from a browser:

```html
<html>
<body>
  <script src="//cdn.jsdelivr.net/pouchdb/5.3.2/pouchdb.min.js"></script>
  <script>
    var db = new PouchDB("mydb");
    db.post({a:1,b:2}, function(err, data){
      console.log(err, data);
    });

    db.replicate.to("http://glynn:3d07659e67fa5a86a06945ec4cdb2754c9fc67bf@localhost:8000/mbaas").on('change', function (info) {
      // handle change
      console.log("change", info);
    }).on('paused', function (err) {
      // replication paused (e.g. replication up to date, user went offline)
      console.log("paused", err)
    }).on('active', function () {
      // replicate resumed (e.g. new changes replicating, user went back online)
      console.log("active");
    }).on('denied', function (err) {
      // a document failed to replicate (e.g. due to permissions)
      console.log("denied",err);

    }).on('complete', function (info) {
      // handle complete
      console.log("complete",info);

    }).on('error', function (err) {
      // handle error
      console.log("error",err);
    });
  
  </script>
  
</body>
```

then PouchDB tries to prod envoy with an OPTIONS request, but as there are no CORS headers in the response, the replication fails.

**Comment by glynnbird** [comment]
This is fixed by adding the following headers to the response:

```
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:accept, authorization
Access-Control-Allow-Origin:http://localhost:8001
```

where the value of `Access-Control-Allow-Headers` is the value received in the incoming `Access-Control-Request-Headers`header and the value of `Access-Control-Allow-Origin` is the derived from the HTTP `referer` header.

**Comment by breusens** [comment]
Do I have to do something to enable CORS? On the server side I wrote:
```
var express = require('express');

var cfenv = require('cfenv');

var app = express();
var session = require('express-session');

    var RedisStore = require('connect-redis')(session);
    
    
    var options = {
      url: 'redis:url'
    };
    
    var sessionHandler = session({
      store: new RedisStore(options),
      secret: 'secret'
    });
    
  
 var opts = {
      couchHost: 'https://secret-bluemix.cloudant.com',
      databaseName: 'myenvoy',
      port: 9000,
      logFormat: 'dev',
      production: false,
      sessionHandler :sessionHandler
    };
    
var envoy = require('cloudant-envoy')(opts);
    
envoy.events.on('listening', function() {
      console.log('[OK]  Server is up');
});
```
when i try 

curl -X POST -d 'username=rita&password=password' https://pouchdbtest.mybluemix.net/_adduser

from the command line it adds rita to envoyusers but in the browser

```
const remoteCouch = 'https://rita:password@pouchdbtest.mybluemix.net';
const sync= function() {
    const opts = {live: true};
    db.replicate.to(remoteCouch,opts).on('denied',function(err) {console.log('denied',err)}).on('error',function(err) {console.log('error',err)}).on('change',function(){console.log('change')}).on('complete',function() {console.log('complete')});
    db.replicate.from(remoteCouch);
}

sync();
```

gives

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (pouchdbtest.mybluemix.net, line 0)
[Error] Failed to load resource: Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin. (pouchdbtest.mybluemix.net, line 0)
[Error] XMLHttpRequest cannot load https://pouchdbtest.mybluemix.net//?_nonce=1484550338067. Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin. (localhost, line 0)

If you are able to point me to the problem, I would be very gratefull.
Brent

**Comment by glynnbird** [comment]
@breusens CORS *should* be enabled in Envoy already https://github.com/cloudant-labs/envoy/blob/master/app.js#L58 let me have a think

**Comment by glynnbird** [comment]
@breusens is it possible you've configured PouchDB's remote URL as

- https://username:password@pouchdbtest.mybluemix.net/

instead of

- - https://username:password@pouchdbtest.mybluemix.net/YOURDBNAME 

?

**Comment by breusens** [comment]
Yes. You are right. I did not realise that is what I should do. Thank you. I corrected that and it looks better. But there is still a problem I think:

[Error] Failed to load resource: Method PUT is not allowed by Access-Control-Allow-Methods. (T8qHdEdkjx7T1TPuWy3XUQ==, line 0)
[Error] XMLHttpRequest cannot load https://pouchdbtest.mybluemix.net/myenvoy/_local/T8qHdEdkjx7T1TPuWy3XUQ%3D%3D?_nonce=1484593637104. Method PUT is not allowed by Access-Control-Allow-Methods. (localhost, line 0)

**Comment by glynnbird** [comment]
It's possible that you're seeing an oddity with using CORS on a localhost domain (see http://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin)

It might be worth trying with "127.0.0.1" or a fake domain name e.g. put

    127.0.0.1    dev.localhost

in your `/etc/hosts` file and try accessing your app from dev.localhost instead.

**Comment by breusens** [comment]
It works. Thank you very much.
