### ISSUE TITLE
Proposed change: power _all_docs using a view

### ISSUE THREAD

**Issue by glynnbird** [cloudant-labs/envoy#26]
At the moment, if you hit `<envoy>/db/_all_docs`, Envoy hits the Cloudant /db/_all_docs endpoint and then filters out documents that do not belong to the requesting user. This has the following disadvantages:

* total_rows value is wrong when we stream the results
* or, if we don't stream the results we could end up using a ton of memory
* this operation gets increasingly insane as the numbers of users increases.

I propose that Envoy creates a view on startup, whose map function is

```
function(doc) {
  if(doc.com_cloudant_meta) {
    for(var i in doc.com_cloudant_meta.auth.users) {
      emit(doc.com_cloudant_meta.auth.users[i], null);
    }
  }
}
```

When Envoy gets a request for /db/_all_docs, instead of proxying to the real "all_docs" endpoint, it hits this view passing `?key="<username>"` which will allow Cloudant to use an index to filter the documents rather than streaming the whole lot.

**Comment by xpqz** [comment]
+1

**Comment by xpqz** [comment]
I can't remember why we didn't do this in the first place.

**Comment by glynnbird** [comment]
Will had a point that a view-powered '_all_docs' could return nulls for document bodies in some cases (eventually consistency).

**Comment by glynnbird** [comment]
Just to summarise discussions we've had about this elswhere
