### ISSUE TITLE
Use mango selector for changes feed filter

### ISSUE THREAD

**Issue by xpqz** [cloudant-labs/envoy#27]
https://github.com/apache/couchdb-couch/pull/162

Cool stuff - and an order of magnitude faster. We should use it to do the user filtering on the changes feed. 

It's currently deployed on BigBlue.

**Comment by xpqz** [comment]
More: https://github.com/apache/couchdb-couch-replicator/commit/986549984be44c7e5cd66f3773d2bdd94f506e5c

**Comment by glynnbird** [comment]
It works:

```
> curl -X POST \ 
-H "Content-type:application/json" \
-d '{"selector":{ "com_cloudant_meta.auth.users": { "$elemMatch": { "$eq": "glynn"}}}}' \ "https://reader:password@reader.cloudant.com/mbaas/_changes?filter=_selector&include_docs=true"
```

only returns that user's docs.

**Comment by xpqz** [comment]
Great. That should be an order of magnitude more efficient, rumour has it.
