### ISSUE TITLE
Let Envoy check it's running against a compatible CouchDB version

### ISSUE THREAD

**Issue by xpqz** [cloudant-labs/envoy#38]
We're relying on features only present in CouchDB2/dbnext -- and very recent ones at that. Could we verify on startup that the backend is compatible?

**Comment by willholley** [comment]
Cloudant's CouchDB 2.0 welcome message is
```
{"couchdb":"Welcome","version":"78f575e","vendor":{"name":"IBM Cloudant","version":"5376","variant":"paas"},"features":["geo"]}
```

CouchDB master is:
```
{"couchdb":"Welcome","version":"b49d069","vendor":{"name":"The Apache Software Foundation"}}
```
- I assume "version" will be 2.0 when it GAs.

Alternatively, we could check for _bulk_get (any build which supports it in the wild also supports Mango on _changes).

**Comment by glynnbird** [comment]
Agreed that on startup, Envoy should check to see if the Cloudant service it is connected to supports the /db/_bulk_get endpoint. If it doesn't, then we should exit with an error message telling the user to:

> If you're using Cloudant, contact support@cloudant.com and ask for your Cloudant account to migrated to the Porter cluster. Apache CouchDB users should ensure they're using the very latest CouchDB code > 2.0

**Comment by willholley** [comment]
> Porter (London) or Sling (Singapore) cluster
