### ISSUE TITLE
[sync-envoy] Create envoy-specific replicators client-side

### ISSUE THREAD

**Issue by xpqz** [cloudant-labs/envoy#47]
[PouchDB, CDTDatastore, Sync-Android - may want to split issue into three]

1. Bypass _changes completely, in favour of either a CQ call or a view.
2. Handle deletions for omitted documents: if an _id I already hold doesn't come back from step 1, it should be assumed to be deleted.
3. Handle `purge` properly.

**Comment by xpqz** [comment]
![img_2623](https://cloud.githubusercontent.com/assets/2690852/15856876/3b8f43c8-2cb0-11e6-90fa-ca107a06ab16.JPG)

**Comment by willholley** [comment]
A couple of thoughts:

For 1. we could do this on the server and construct a _changes response based on a query under the hood (e.g. client POSTs to _changes with a query).

Regarding purge, what Couchbase do is add a new type of entry to _changes - "removed" - which is an instruction to the client to purge a document. We could potentially do something similar if constructing a _changes feed in envoy. It's also worth noting that Couchbase Lite is the only client lib that actually implements purge today.

**Comment by glynnbird** [comment]
Created pouchdb-envoy. Mark has created Cloudant Sync PoCs too.
