### ISSUE TITLE
[sync-envoy] Remove all endpoints not explicitly required for the sync-envoy protocol

### ISSUE THREAD

**Issue by xpqz** [cloudant-labs/envoy#48]
See https://github.com/cloudant-labs/envoy/issues/47

Keep the focus on the sync, should remove:

1. changes
2. delete document
3. find
4. get document
5. insert document
6. update document
7. post index

**Comment by willholley** [comment]
we need changes and get document to remain sync compatible with CouchDB. Is that no longer a goal?

**Comment by xpqz** [comment]
We discussed stuff at length with Glynn and Mike - and one of the realisations was that we can't both be fully couchdb compatible and efficient at the same time. Powering changes off either all_docs or Mango means that we break deletions. So making a tweak to the client side of the replication seems the only way to be able to allow for efficient replication with "millions" of users and thousands of docs per user.

**Comment by xpqz** [comment]
I'm parking this for now.
