### ISSUE TITLE
idea: integrate superlogin

### ISSUE THREAD

**Issue by willholley** [cloudant-labs/envoy#5]
A common requirement for a complete application tier alongside Cloudant is to handle user signup/login. Perhaps we should integrate https://github.com/colinskow/superlogin or provide a sample application which does?

**Comment by glynnbird** [comment]
Notes from 27th May meeting:
* @willholley says that SuperLogin is highly thought of in the PouchDB community
* general feeling that we want to make small steps towards a user model solution
* superlogin uses [Passport](http://passportjs.org/) for OAuth, and Passport is a well used solution for login on Node.js apps
* we also want to ensure that a user can deploy Envoy very easily - in the first instance, we don't want to oblige them to register Facebook apps and deal with OAuth tokens etc. 

Passport has many "[strategies](http://passportjs.org/docs)" that it can use for authentication (facebook, saml, linkedin etc). We decided it would be good to have a simple, hard-coded Passport strategy that mimics the current state of authentication e.g. anyone who presents with Basic auth credentials is allowed it. This would allow our tests to continue working and for first-time installers of Envoy to see what it does without too much effort.

When a user wants to lockdown their installation they can switch to another Passport strategy.

**Comment by glynnbird** [comment]
see https://github.com/cloudant-labs/envoy/pull/34

**Comment by glynnbird** [comment]
Using _users

**Comment by numerized** [comment]
Hi there, seems like it's possible to integrate envoy with superlogin but how ?
I can't figure it out.

**Comment by paulreimer** [comment]
The PR mentioned above (#34) -- and the PR that it mentions (#37), were not merged.

I'm also interested in integrating superlogin and/or directly using Passport. What is the recommended way? Is it deploying superlogin and envoy separately, and they both share the `_users` database? Does this "Just Work", or are there app/settings changes needed?
