### ISSUE TITLE
bulk_get is broken

### ISSUE THREAD

**Issue by willholley** [cloudant-labs/envoy#64]
https://github.com/cloudant-labs/envoy/blame/master/lib/routes/bulk-get.js#L58 got broken when we changed the metadata object. The line should be:

```
return utils.isMine(row.docs[0].ok, req.session.user.name);
```
Our tests apparently don't exercise this code path - I'm not sure why - but it breaks PouchDB replication with lots of documents. Whilst the fix is trivial, we should add test coverage at the same time.

**Comment by xpqz** [comment]
The json that _bulk_get generates is rather opaque and convoluted. I'm sure there is some reason for this I can't see.

**Comment by glynnbird** [comment]
The reason the tests didn't catch this is that the logic doing most of the assertions is in a `response.results.forEach(...)` statement, but response.results is empty :)
