### ISSUE TITLE
Replication doesn't work through envoy

### ISSUE THREAD

**Issue by burzakovskiy** [cloudant-labs/envoy#80]
While replication between mobile device and Cloudant db works perfectly using [sync-android](https://github.com/cloudant/sync-android) library, I get always 401 error trying to do that through envoy. User with name "user" and password "password" was manually created in envoyusers db and authentication works ok.
URI for replication http://user:password@/< myenvoyhost >:80/mbaas
```E/PushStrategy: Batch 0 ended with error:
CouchException: error: Unknown error, reason: Unkown reason, statusCode: 401, msg: Error deserializing server response, cause: java.io.FileNotFoundException: http://<myenvoyhost>:80/mbaas```

**Comment by xpqz** [comment]
Hi. Two things: you may be running against a version of Cloudant which isn't Envoy-compatible - we rely on some features only available in Cloudant releases based on CouchDB2.0. You need a 'dbnext' cluster for this (BigBlue or Porter) - or run the actual CouchDB2 in a Docker which is what Envoy itself does for its testing:
```bash
#!/usr/bin/env bash

if [ ! -z $TRAVIS ]; then
	# Install CouchDB Master
	docker run --ulimit nofile=2048:2048 -d -p 3001:5984 klaemo/couchdb:2.0-dev --with-haproxy \
	    --with-admin-party-please -n 1
	COUCH_PORT=3001

	# wait for couchdb to start
	while [ '200' != $(curl -s -o /dev/null -w %{http_code} http://127.0.0.1:${COUCH_PORT}) ]; do
	  echo waiting for couch to load... ;
	  sleep 1;
	done
fi
```
Secondly, it could be that sync-android isn't Envoy-friendly - not sure we've tested this.

**Comment by burzakovskiy** [comment]
Well, I used Cloudant version supplied within Envoy app for Bluemix.

**Comment by xpqz** [comment]
That's not currently sufficient, unfortunately - the 'standard' Cloudant account you get with Bluemix is running on an older version. We should make that clear on the README.

**Comment by xpqz** [comment]
Send an email to support@cloudant.com and request that your account be moved to the cluster 'porter' which should be running the latest & greatest version of Cloudant you need for Envoy.

**Comment by burzakovskiy** [comment]
@xpqz here is what support says
"We are not able to move your Bluemix account to porter as it is not a Bluemix cluster. Maybe ibm009 would be a better option for you? It is a shared Bluemix cluster."

Is  ibm009 right option?

**Comment by willholley** [comment]
@burzakovskiy I don't think there's actually a good option on Bluemix today. Your best option is probably to create a Cloudant account at http://cloudant.com, specifying the Porter cluster, and provide those credentials to your Bluemix application.

**Comment by burzakovskiy** [comment]
@willholley so ibm009 is running on Envoy incompatible Cloudant version too?

**Comment by willholley** [comment]
@burzakovskiy not ibm009, no.

@xpqz / @glynnbird another option here would be to fake _bulk_get similar to the way PouchDB does. In fact, we could even use PouchDB as the HTTP client and get the shim for free.

**Comment by glynnbird** [comment]
If we were faking bulk get in Envoy, (talking to a Cloudant/Couch cluster that didn't support _bulk_get) we would probably need to make lots of queries in parallel to get the performance. i.e if the client asks for 100 doc ids, we set off 100 GET /db/docid?revs_info=true requests going (with a maximum parallelism of, say, 10) and then reply back to the client when they've all replied.

Is that what you mean @willholley ?

**Comment by willholley** [comment]
Basically, yes. The primary reason we need bulk get is that the overhead of making many client <-> server requests is high, particularly when there is high network latency (e.g. mobile apps). If envoy is colocated in the same DC as Cloudant, the overhead is much less, so a shimmed bulk_get is still a win.

We can make a similar argument for HTTP 2.0 support - it reduces the overhead of multiple requests between the client and envoy which should be a net win if envoy <-> Cloudant latency is minimal.
